version: '3'
services:
  react-vite:
    container_name: react-vite
    build: .
    image: my-portfolio-node
    tty: true
    volumes:
      - .:/app/my-portfolio
      - /app/my-portfolio/frontend/node_modules
    ports:
      - "3000:3000"
    command: npm run dev
  mock-server:
    container_name: mock-server
    build: .
    image: my-portfolio-node
    tty: true
    volumes:
      - .:/app/my-portfolio
      - /app/my-portfolio/frontend/node_modules
    ports:
      - "4000:4000"
    command: npm run mock